### ISSUE TITLE
Crash on branch Book_part_1.

### ISSUE THREAD

**Issue by babogoos** [hungyanbin/ReactiveStickyNote#4]
Sometime build with #Bool_part_1 branch will  crash by follow exception.

> FATAL EXCEPTION: main
Process: com.yanbin.reactivestickynote, PID: 7274
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double
	at com.yanbin.reactivestickynote.data.FirebaseNoteRepository.documentToNotes(FirebaseNoteRepository.kt:83)
	at com.yanbin.reactivestickynote.data.FirebaseNoteRepository.onSnapshotUpdated(FirebaseNoteRepository.kt:61)
	at com.yanbin.reactivestickynote.data.FirebaseNoteRepository._init_$lambda-1(FirebaseNoteRepository.kt:27)
	at com.yanbin.reactivestickynote.data.FirebaseNoteRepository.$r8$lambda$IicgOeux2b4Po4miy9VM2tWGj9Q(Unknown Source:0)
	at com.yanbin.reactivestickynote.data.FirebaseNoteRepository$$ExternalSyntheticLambda0.onEvent(Unknown Source:4)
	at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2$com-google-firebase-firestore-Query(Query.java:1133)
	at com.google.firebase.firestore.Query$$ExternalSyntheticLambda2.onEvent(Unknown Source:6)
	at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0$com-google-firebase-firestore-core-AsyncEventListener(AsyncEventListener.java:42)
	at com.google.firebase.firestore.core.AsyncEventListener$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	
It should be use safety cast.

`val positionX = data[FIELD_POSITION_X] as? Double? ?: 0`
`val positionY = data[FIELD_POSITION_Y] as? Double? ?: 0`

**Comment by hungyanbin** [comment]
Thanks for reporting, already fixed on all branches.
